# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f8825b32710134ec2c110a60c97cb3ed1457a55f661df9d3baa7285238de23b4385966113ef61871b1cac214b61ae8a6b8e2316a1389fd72304b97e3e53cbcf

test:
  secret_key_base: a97ff80398dbd7c0612eafbe963026dae371d84f07a5cda0d7ef56ea7cb252886d47c0366485b3737c7f04f593466958a24b5f4015f7c70accc9eecc60ef1226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
